export const GET_PROMOTIONS = "GET_PROMOTIONS";
export const ADD_PROMOTION = "ADD_PROMOTION";
export const DELETE_PROMOTION = "DELETE_PROMOTION";
export const SELECT_PROMOTION = "SELECT_PROMOTION";
export const CLEAR_PROMOTION_STATE = "CLEAR_PROMOTION_STATE";
export const GET_PROMOTION = "GET_PROMOTION";
